USE [master]
GO

/****** Object:  Database [DB_FleetService]    Script Date: 10/12/2020 12:49:20 p. m. ******/
CREATE DATABASE [DB_FleetService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_FleetService', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DB_FleetService.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_FleetService_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DB_FleetService_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_FleetService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_FleetService] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_FleetService] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_FleetService] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_FleetService] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_FleetService] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_FleetService] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_FleetService] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_FleetService] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_FleetService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_FleetService] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_FleetService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_FleetService] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_FleetService] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_FleetService] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_FleetService] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_FleetService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_FleetService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_FleetService] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_FleetService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_FleetService] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_FleetService] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_FleetService] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_FleetService] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_FleetService] SET  MULTI_USER 
GO

ALTER DATABASE [DB_FleetService] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_FleetService] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_FleetService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_FleetService] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_FleetService] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_FleetService] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_FleetService] SET  READ_WRITE 
GO

